### ISSUE TITLE
App fixes

### ISSUE THREAD

**Issue by ErlendNilsen** [DrMattG/HarvestGolem#33]
Based on the current version under the master branch, I have these comments; 

**Tab «historiske data»:** 

- [ ] Nedtrekksmeny er forvirrende (vis «Hele landet» eller «Alle regioner» når man velger alle, ikke «Region_1, Region_2» osv).  
- [x] Dotted line må relateres til regionale bestandsmål. 
- [x] Tooltip viser forvirrende informasjon. Fjern denne dersom det er vanskelig å endre. 

**Tab "Prognosemodell":** 
- [ ] Nedtrekksmeny er forvirrende (vis «Hele landet» eller «Alle regioner» når man velger alle, ikke «Region_1, Region_2» osv). 
- [x] Oppsummeringstabell -> Tab «Prognosis» skal være «Prognose». 
- [x] Oppsummeringstabell -> Under tab "prognosis": Tabellen viser NA i flere celler. Rund av til 1 desimal i tabellen. 
- [x] Oppsummeringstabell -> Tabellen «prediktiv» bør endres til «Prognose to år fram i tid». 
- [x] Oppsummeringstabell -> Under tab "prediktiv": Endre harvest_level til «kvotealtternativ». 
- [x] Oppsummeringstabell -> Under tab "prediktiv": Oversett resten til Norsk (e.g. fitted = «prognose».) 
- [x] Oppsummeringstabell -> Under tab "prediktiv": Holder med 75% CI slik som i den andre tabellen. 
- [x] Grafisk oppsummering -> Får feilmeldinger (e.g. «object smean not found», «could not find function “dataInput2”), ikke noe output 
- [x] Grafisk oppsummering -> Figur under “prediktiv”: Skriftstørrelsen er for liten. 
- [x] Grafisk oppsummering -> Figur under “prediktiv”: Endre tabnavn til “Prognose to år fram i tid».

**Comment by DrMattG** [comment]
https://github.com/DrMattG/HarvestGolem/issues/34
